### ISSUE TITLE
How to display extended desktop?

### ISSUE THREAD

**Issue by ghost** [mrenrich84/vnc_virtual_display_linker#1]
I configured my second virtual monitor as 1920x1200 portrait, and I got duplicated output (same view as built in screen of my laptop).
How to change this to side by side extended desktop on two monitors?
Weird thing, first time I'd run Your script it behaved properly and made my desktop extended. 
But it stopped as soon as I changed the resolution (and deleted monitors via D option)

Best regards, superb script, gets into the point in notime.

**Comment by mrenrich84** [comment]
Hey thanks!

There must a glitch somewhere, thing is it was a quick & dirt solution I came up with.
I would like to find some time to refactor it.

Meantime, if you are on Ubuntu, have you tried getting into the "screen display" menu and see if another screen has been created?
You can use the script to create a second monitor with the desired resolution and then hack your problem with that menu as a temp solution.
