### ISSUE TITLE
new monitor and Nvidia proprietary driver

### ISSUE THREAD

**Issue by MarkoSchuetz** [mrenrich84/vnc_virtual_display_linker#10]
It seems the Nvidia proprietary driver does not support a virtual monitor

    X Error of failed request:  BadName (named color or font does not exist)
      Major opcode of failed request:  140 (RANDR)
      Minor opcode of failed request:  16 (RRCreateMode)
      Serial number of failed request:  41
      Current serial number in output stream:  41
    xrandr: cannot find output "VIRTUAL1"
    warning: output VIRTUAL1 not found; ignoring

So the approach will not work on that driver.

**Comment by mrenrich84** [comment]
is that on Ubuntu 18.04?

**Comment by MarkoSchuetz** [comment]
This is on Manjaro. Kernel version is 5.4.30. Nvidia driver 440.82, xorg-server 1.20.8

**Comment by mrenrich84** [comment]
have you tried this: https://github.com/mrenrich84/vnc_virtual_display_linker/issues/4#issuecomment-447587604 ?

sorry I'm not maintaining this code anymore

**Comment by kvngvikram** [comment]
I am facing the same problem as well. No VIRTUAL1 when using Nvidia.
So I created the file as described in [#4 (comment)](https://github.com/mrenrich84/vnc_virtual_display_linker/issues/4#issuecomment-447587604). It works now, with my iPad/tablet as a true second monitor but with few issues. 
I am using Pop_OS. After adding the file and restart or re logging in, my Nvidia graphics card is never being used. Only intel gpu is being used even if I am not using the second screen. I have to manually remove or rename the file, logout and login to switch back to using Nvidia graphics.
When I am using intel's graphics (when the file is present), my desktop has problems as shown in image. These black patches form when run the script to start using second screen and stay there until i switch back to Nvidia.
![Screenshot from 2020-06-23 18-42-30](https://user-images.githubusercontent.com/32128870/85420410-c861eb80-b590-11ea-8be0-b1b6bfc9cb63.png)

**Comment by erikologic** [comment]
Hey @kvngvikram,
I have a dual GPU Intel / Nvidia and haven't seen those problems, so sorry but I can't help you with that.
Also, I switched my main developing platform and I am not maintaining this tool anymore, as specified in the README.
Please, feel free to fork the project and pick it up!
