### ISSUE TITLE
wrong position of second desktop on tablet 

### ISSUE THREAD

**Issue by ferdiga** [mrenrich84/vnc_virtual_display_linker#2]
I use a nexus 7 with bVNC free and Ubuntu 16.04

the desktop on the tablet is not positioned correctly on the top of the screen, but about 300px "downward"
hence the top of the physical screen is black and the lower part of the virtual scren is cut off.

any suggestions?

**Comment by mrenrich84** [comment]
A couple of necessary questions:
1) Have you configured the resolution in the script of the virtual monitor to match the one from your Nexus 7? Have you tried just in the menu or also hardcoding it in the script (line 39-40)?
2) Have you tried opening the Ubuntu monitor setup tool and playing around there if it fixed the problem somehow? If you will try and it works, can you please report how you solved it?
 
The script basically does a couple of things:
- configure a virtual monitor with xrandr
- launch x11vnc to clip the virtual monitor space in a vnc session

I don't have a Nexus 7 at hand and I never experienced that problem so it would be hard for me to investigate it and find a solution.
I guess you'll have to play with these commands and see what you come up for fixing your issue, I'm sorry.

I'd be happy to be of more help and implement your solution in this script, so keep me posted!
