### ISSUE TITLE
Problems to run the script

### ISSUE THREAD

**Issue by Lukastos** [mrenrich84/vnc_virtual_display_linker#3]
I have trouble to run the script.

I have lubuntu 16.04 and I have python 3.5 with the right package.

At first I got:
`  File "vnc_virtual_display_linker.py", line 133
    print text + " [" +  str(var) + ']:'
             ^
SyntaxError: invalid syntax
`

So I tried to add brackets for all the print functions (this seemed to be the problem), but then I got:
Traceback (most recent call last):
  File "vnc_virtual_display_linker.py", line 200, in <module>
    main_menu()
  File "vnc_virtual_display_linker.py", line 143, in main_menu
    screen_manager = ScreenManager()
  File "vnc_virtual_display_linker.py", line 66, in __init__
    self.new_monitor()
  File "vnc_virtual_display_linker.py", line 73, in new_monitor
    self.set_xrandr_mode_and_x11vnc_clip(conf.virtual_monitor.width, conf.virtual_monitor.length)
  File "vnc_virtual_display_linker.py", line 129, in set_xrandr_mode_and_x11vnc_clip
    self.conf[self.get_orientation()].xrandr_mode.data = self.get_xrandr_mode_data( width, length)
  File "vnc_virtual_display_linker.py", line 118, in get_xrandr_mode_data
    for line in subprocess.check_output("gtf {0} {1} 60".format(width, length), shell=True).split("\n"):
TypeError: a bytes-like object is required, not 'str'
`

I tried to run it with python 2.7, no difference.

Any idea? I'm really interested in your script :)

**Comment by mrenrich84** [comment]
Hey any luck with it?
I am launching it with the default python interpreter in Ubuntu 16.04 which should be 2.7
Is a bit weird because you are the only one getting errors...
Have you tried splitting that statement into different lines?

**Comment by xlith** [comment]
@Lukastos i believe you have done something wrong when you tried to run it with python2.7 . I got the exact error when i tried to run with python3 but i with 2.7 it's working.
