### ISSUE TITLE
No second screen

### ISSUE THREAD

**Issue by udohatestrees** [mrenrich84/vnc_virtual_display_linker#5]
Hello there,
my Debian 9 install don't have an xrandr output named "VIRTUAL1". Instead I changed the variable in the script to an existing output, let's say "VGA-1".
My problem is, that whatever I try, I can only see my main screen on my android tablet. The tablet is not recognized as a second screen. Instead of getting more screen estate I mirror my existing screen onto the tablet.
Do you have any idea why this happens?
If I change the script to its original state using VIRTUAL1 the same happens but I get an error message that VIRTUAL1 is not found.

**Comment by mrenrich84** [comment]
on the menu:
press a to activate the adbc connection
press n to create a new virtual monitor
press s to start vnc

**Comment by derfshaya** [comment]
For me, it worked by scrolling the VNC view to the right.
